package com.monitoratec.tokenservice.vtswalletservice.repository;

import com.monitoratec.tokenservice.vtswalletservice.domain.model.ProvisionTokenProvisionedTokensForAPaymentInstrumentModel;
import org.springframework.data.mongodb.repository.MongoRepository;

public interface ProvisionTokenProvisionedTokensForAPaymentInstrumentRepository extends MongoRepository<ProvisionTokenProvisionedTokensForAPaymentInstrumentModel,String> {
}
